// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {patcher} from '../models';
import {editor} from '../models';

export function ApplyTranslation(arg1:main.ApplyRequest):Promise<patcher.ApplyResult>;

export function ExportTranslationJSON(arg1:Array<editor.TranslationRow>):Promise<string>;

export function GetEditorToolingStatus():Promise<editor.ToolingStatus>;

export function GetGameStatus():Promise<main.AppStatus>;

export function ImportTranslationJSON():Promise<Array<editor.TranslationRow>>;

export function InstallEditorTooling():Promise<editor.ToolingStatus>;

export function LoadTranslationEditor():Promise<editor.EditorData>;

export function SaveTranslationEditor(arg1:Array<editor.TranslationRow>):Promise<void>;
