// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTranslation(arg1) {
  return window['go']['main']['App']['ApplyTranslation'](arg1);
}

export function ExportTranslationJSON(arg1) {
  return window['go']['main']['App']['ExportTranslationJSON'](arg1);
}

export function GetEditorToolingStatus() {
  return window['go']['main']['App']['GetEditorToolingStatus']();
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}

export function ImportTranslationJSON() {
  return window['go']['main']['App']['ImportTranslationJSON']();
}

export function InstallEditorTooling() {
  return window['go']['main']['App']['InstallEditorTooling']();
}

export function LoadTranslationEditor() {
  return window['go']['main']['App']['LoadTranslationEditor']();
}

export function SaveTranslationEditor(arg1) {
  return window['go']['main']['App']['SaveTranslationEditor'](arg1);
}
