// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTranslation(arg1) {
  return window['go']['main']['App']['ApplyTranslation'](arg1);
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}
