// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {patcher} from '../models';

export function ApplyTranslation(arg1:main.ApplyRequest):Promise<patcher.ApplyResult>;

export function GetGameStatus():Promise<main.AppStatus>;
